app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
config/environments/production.rb
config/initializers/devise.rb
db/migrate/20201124103951_add_info_to_users.rb
db/schema.rb

adding user information to table as well as basic user configs

---

app/assets/stylesheets/config/_fonts.scss
app/controllers/sports_classes_controller.rb
app/views/sports_classes/index.html.erb
config/routes.rb

Place-holder bootstrap colours used for the buttons.

Index page

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_navbar.scss

Navbar fix

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_sports-class-modal.scss
app/controllers/sports_classes_controller.rb
app/models/sports_class.rb
app/views/sports_classes/index.html.erb
app/views/sports_classes/new.html.erb

class show design. added a background color to the overall body and adapted controllers and models of sports_class

class show design + some adjustments

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_sports-class-modal.scss
app/assets/stylesheets/components/_sports-classes-cards.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_all-classes.scss
app/assets/stylesheets/pages/_index.scss
app/views/sports_classes/index.html.erb

I did the card design for the index page. nothing to bundle.

Card design

---

app/controllers/class_bookings_controller.rb
app/controllers/sports_classes_controller.rb
app/models/user.rb
app/policies/class_booking_policy.rb
app/views/sports_classes/index.html.erb
config/routes.rb
db/seeds.rb

Bookings display

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_searchbar.scss
app/controllers/sports_classes_controller.rb
app/models/sports_class.rb
app/models/trainer.rb
app/views/pages/home.html.erb
app/views/sports_classes/index.html.erb
db/seeds.rb

Search bar with some basic styling created. After it has been merged there is some set up to do, under elasticsearch in the lecture source code:
https://kitt.lewagon.com/camps/490/lectures/05-Rails%2F09-Airbnb-SMTP 
Also the models would need to be reindexed from the rails c, such as SportsClass.reindex

Homepage search - set up needed when pulled!!

---

app/assets/stylesheets/components/_booked-sports-classes-cards.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_index.scss
app/views/sports_classes/copy_index.htm.erb
app/views/sports_classes/index.html.erb

Bookings display cards

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/reviews.scss
app/assets/stylesheets/pages/_trainershow.scss
app/controllers/reviews_controller.rb
app/models/review.rb
app/models/sports_class.rb
app/models/trainer.rb
app/models/user.rb
app/views/reviews/new.html.erb
app/views/trainers/show.html.erb
config/routes.rb
db/migrate/20201128224204_remove_sports_class_reference_from_reviews.rb
db/migrate/20201128224650_add_trainer_reference_to_reviews.rb
db/schema.rb
db/seeds.rb

Includes routes edit to put the reviews nested under trainers instead of sports class + 2 new migrations to fix the schema + styling of reviews + the fix on seeds

Review fix

---

app/assets/stylesheets/components/_filter-cards.scss
app/assets/stylesheets/components/_index.scss
app/views/reviews/new.html.erb
app/views/shared/_filter-cards.html.erb
app/views/sports_classes/index.html.erb

Filter cards

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/javascript/plugins/init_star_rating.js
package.json
yarn.lock

Star reviews

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/javascript/plugins/init_star_rating.js
app/views/pages/profile.html.erb
app/views/shared/_booked-sport-class-card.html.erb
app/views/shared/_modal-class.html.erb
app/views/shared/_profile-created-classes.html.erb
app/views/shared/_profile-upcoming-classes.html.erb
app/views/shared/_sport-class-card.html.erb
app/views/sports_classes/index.html.erb
package.json
yarn.lock

Split cards and modals into partials

Profile cards

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_icons.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_sports-class-modal.scss
app/views/pages/profile.html.erb
app/views/sports_classes/new.html.erb
app/views/trainers/new.html.erb
app/views/trainers/show.html.erb

implemented back buttons

---

Gemfile
Gemfile.lock
app/controllers/sports_classes_controller.rb
app/javascript/packs/application.js
app/views/layouts/application.html.erb
app/views/shared/_booked-sport-class-card.html.erb
app/views/shared/_profile-created-classes.html.erb
app/views/shared/_profile-upcoming-classes.html.erb
app/views/sports_classes/show.html.erb
config/application.rb
config/initializers/cors.rb
db/migrate/20201130161033_add_room_to_sports_classes.rb
db/schema.rb

please db:migrate and db:seed. everytime a class is created, it creates a room

streaming in place

---

app/controllers/class_bookings_controller.rb
app/controllers/subscriptions_controller.rb
app/views/pages/profile.html.erb
app/views/shared/_modal-class.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sport-class-card.html.erb
app/views/trainers/show.html.erb
db/migrate/20201203094048_add_credits_to_subscriptions.rb
db/schema.rb

You'll need to rails db:migrate AND rails db:seed

Fix memberships

---

app/controllers/class_bookings_controller.rb
app/controllers/sports_classes_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_sweetalert.js
app/javascript/plugins/init_sweetalert_all.js
app/views/shared/_booked-sport-class-card.html.erb
app/views/shared/_modal-class.html.erb
app/views/shared/_sport-class-card.html.erb
app/views/trainers/show.html.erb

Fixed buttons and refactored code, deactivated sweet alerts

Sweet alerts

---

app/controllers/sports_classes_controller.rb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/sports_classes/show.html.erb

- full screen on streaming
- chat in streaming
- class streaming rooms expire after 24 hours
- discover button in the navbar
- some minor validations on the newsletter sign up

Email validation

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_tabs.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/sports_classes_controller.rb
app/views/pages/profile.html.erb
app/views/pages/settings.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_profile-created-classes.html.erb
app/views/shared/_profile-upcoming-classes.html.erb
config/routes.rb

- Split the User profile and the settings info into two in the dropdown
- Styled the dropdown + the navbar + the my classes page
- My classes are structured in tabs
- Explore button in the navbar

user profile and setting are split

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/assets/stylesheets/pages/_settings.scss
app/views/pages/profile.html.erb
app/views/pages/settings.html.erb
app/views/shared/_class-stats.html.erb
db/seeds.rb

- trainer stats in the settings section. 
- also fixed the seeds

Trainer stats

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/reviews.scss
app/assets/stylesheets/pages/_trainershow.scss
app/controllers/trainers_controller.rb
app/policies/sports_class_policy.rb
app/policies/trainer_policy.rb
app/views/reviews/_new.html.erb
app/views/shared/_reviews-listed.html.erb
app/views/shared/_trainer-modal-class.html.erb
app/views/shared/_trainer-upcoming-classes.html.erb
app/views/sports_classes/index.html.erb
app/views/sports_classes/new.html.erb
app/views/trainers/edit.html.erb
app/views/trainers/show.html.erb
config/routes.rb

- styled the trainer page a bit more, 
- added the reviews section to trainers page,
- we now see only upcoming classes on trainer page
- added the update option to the trainer page for trainers to edit their trainer profile
- when signed in, the root path is the index page. When not signed in, we land on the home page
- refactored the trainer view by replacing all iterations with collections in partials.

Styling ux

---

app/assets/stylesheets/components/_inputs.scss
app/views/shared/_booked-sport-class-card.html.erb
app/views/shared/_modal-class.html.erb
app/views/shared/_profile-created-classes.html.erb
app/views/shared/_profile-upcoming-classes.html.erb
app/views/shared/_sport-class-card.html.erb
app/views/shared/_trainer-upcoming-classes.html.erb
app/views/sports_classes/new.html.erb
db/migrate/20201223150317_change_duration_to_be_integer_in_sports_classes.rb
db/schema.rb

- made the migration to change duration from string to integer in sports_classes table
- adjusted the form 
- added minutes after the input amount in the views

Change duration

---

app/assets/stylesheets/pages/_home.scss

fixed home page

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

- changed logo to new logo
- added content to home page
- made home page responsive
- slight adjustment on the navbar dropdown for mobile

Responsive home

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/shared/_booked-sport-class-card.html.erb
app/views/shared/_class-stats.html.erb
app/views/shared/_modal-class.html.erb
app/views/shared/_profile-created-classes.html.erb
app/views/shared/_profile-upcoming-classes.html.erb
app/views/shared/_sport-class-card.html.erb
app/views/shared/_trainer-modal-class.html.erb
app/views/shared/_trainer-upcoming-classes.html.erb

- changed time zone code on cards and modals
- basic restyling of the forgot password and send confirmation email pages

Time zone fix

---

app/controllers/trainers_controller.rb
app/views/shared/_trainer-modal-class.html.erb
app/views/shared/_trainer-upcoming-classes.html.erb

fixed trainer show bug

---

Gemfile
Gemfile.lock
app/javascript/packs/application.js
app/javascript/plugins/local-time.js
app/views/shared/_booked-sport-class-card.html.erb
app/views/shared/_class-stats.html.erb
app/views/shared/_modal-class.html.erb
app/views/shared/_profile-created-classes.html.erb
app/views/shared/_profile-upcoming-classes.html.erb
app/views/shared/_reviews-listed.html.erb
app/views/shared/_sport-class-card.html.erb
app/views/shared/_trainer-modal-class.html.erb
app/views/shared/_trainer-upcoming-classes.html.erb

solution to displaying times in browser time. This a temporary fix as the local-time gem is not being maintained. bundle install required
In the /app/javascript/plugins folder, I placed the code local-time.js directly from the github repo from the local-time solution that was made by basecamp. Then, I added the following bit of code to /app/javascript/packs/application.js
import LocalTime from 'helpers/local-time'
LocalTime.start()
17:49
I found this solution here: https://stackoverflow.com/questions/65388487/rails-local-time-gem-not-running-js because the basecamp(founders of rails) set up doesnt work properly anymore since the last update of rails

added local-time gem and js plugin

---

app/controllers/confirmations_controller.rb
app/controllers/registrations_controller.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/layouts/mailer.html.erb
app/views/sports_class_mailer/new_class_confirmation.html.erb
app/views/trainer_mailer/welcome_trainer.html.erb
app/views/user_mailer/welcome_user.html.erb
config/environments/production.rb
config/routes.rb
test/controllers/confirmations_controller_test.rb
test/controllers/registrations_controller_test.rb

- All transactional emails have been customized
- user will be automatically signed in and redirected to search page after confirming email address from the email

Customized transactional emails + user signed in after confirmation

---

app/assets/stylesheets/components/_form.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/locales/de.yml
config/locales/en.yml

Spelling mistakes fixed
Standardised form style
New style on forms - 
headings & inputs & buttons- increased font, changed letter-spacing, uppercase
input border - color change
slight margin change validation button

New signup form

---

app/views/sports_classes/index.html.erb

Added the widget on the index page with a video of me telling people what's new on yance.

video ask widget for personalized messaging

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_sports_classes.scss
app/views/shared/_footer.html.erb

changed link to instagram with target blank, to open in a new tab

---

app/assets/stylesheets/components/_chatroom_show.scss
app/assets/stylesheets/components/_messages.scss
app/assets/stylesheets/components/_sports-class-chatroom-cards.scss
app/views/messages/_message.html.erb
app/views/sports_class_messages/_sports_class_message.html.erb

Message styling has been changed to avoid having to refresh for some styling to be applied.

message styling changed, no longer needs to be refreshed
